### PR TITLE
Mocking API

### PR DESCRIPTION
**Pull request by angelodipaolo**
## Summary

- Introduces `Session` and `DataTask` protocols
- Introduces a simple mocking API.
- Refactors unit tests to use mock sessions and responses, preventing requests from being sent over the network
- Adds more unit tests, **increasing code coverage to 99%**

## Session

Introduced `Session` and `DataTask` protocols to decouple `NSURLSession` and `NSURLSessionDataTask` from `ServiceTask` and `WebService`. These protocols enable code to mock the session and data task objects so that unit tests can be performed without sending requests over the network. The framework provides implementations that make `NSURLSession` conform to `Session` and `NSURLSessionDataTask` conform to `DataTask`

- Deprecates `SessionDataTaskDataSource` protocol in favor of `Session`
- Deprecates WebService's `dataTaskWithRequest(request:completionHandler)` method. Instead, use `dataTask(request:completion:)`.
- Deprecates WebService's `dataTaskSource` property. Session protocol and the `session` property should be used instead.

```
public protocol Session {
    public func dataTask(request request: URLRequestEncodable, completion: (NSData?, NSURLResponse?, NSError?) -> Void) -> DataTask
}

public protocol DataTask {
    public var state: NSURLSessionTaskState { get }
    public func suspend()
    public func resume()
    public func cancel()
}
```

## Mocking API

- Create response stubs from any type that implements the `MockableDataTaskResult` protocol.
- Easy mocking of `NSHTTPURLResponse` and `NSData` objects via `MockResponse`.
- Add mocked responses as stubs to a session via `MockSession`.

```
let expectation = expectationWithDescription("responseAsBrews handler called when JSON is valid")

// create a mock session
let session = MockSession()

// create a mocked response for some JSON data
let brewerJSON = ["name": "Long Trail Brewing Company", "location": "Vermont"]
let mockedResponse = MockResponse(statusCode: 200, json: ["brewers": [brewerJSON]])

// add a mocked response as a stub to the session
session.addStub(mockedResponse)

// inject mock session as your web service's session
let service = WebService(baseURLString: "http://brewhapi.herokuapp.com/")
service.session = session

// make a request that will be fulfilled by the mocked response
service
    .fetchBrewWithBrewID("12345")
    .responseAsBrews { brews in
        XCTAssertEqual(brews.count, 1)
        expectation.fulfill()
    }.updateErrorUI { error in
        XCTFail("updateErrorUI handler should not be called when JSON is valid")
    }
    .resume()

waitForExpectationsWithTimeout(2.0, handler: nil)
```

See [Mocking API docs](https://github.com/Electrode-iOS/ELWebService/blob/893ce9c2be6b119ef3b3b8d92ab69ef101a9e0aa/docs/Programming-Guide.md#mocking) for more info.

### CODE REVIEW

**Comment by steveriggins** [comment]
Have you checked to see if NSURLProtocol can be used to mock NSURLSession? It's a class based old protocol, but hooks at the OS level.

**Comment by steveriggins** [comment]
Is this similar to SDWebService's stack of responses? FIFO?

**Comment by steveriggins** [comment]
What I REALLY like is the abstraction of the session. If I am reading this right, we can add any custom sessions? For example a more sophisticated logic based one?

**Comment by angelodipaolo** [comment]
@steveriggins I'm not sure how `NSURLProtocol` could be used to mock `NSURLSession` but yes, you can add custom sessions now via the `Session` protocol. the goal was to enable session mocking but it could also be used to do something custom.

**Pull request merged**
