### PR TITLE
Add support for asynchronous request body data

### PR DESCRIPTION
**Pull request by nonsensery**
### What problem does this PR address?

We frequently use `ELWebService` to send JSON requests. That typically involves (a) generating the request body synchronously on the main thread, and (b) either ignoring encoding errors, or adding a separate code path to handle them.

Here's a simplified example:

```swift
let requestBody: Data

do {
  requestBody = try JSONEncoder().encode(requestBodyModel)
} catch {
  // handle (or ignore) encoding errors
}

service.POST("some/path")
  .setBody(requestBody)
  .responseJSON { … }
  .responseError {
    // handle other errors
  }
  .resume()
```

### What's the solution in this PR?

I added overrides for `ServiceTask.setBody()` and `ServiceTask.setJSONData()` that accept a closure that returns the data. The closure is run (on a background thread) when the task is first resumed.

Here's an example:

```swift
service.POST("some/path")
  .setBody { try JSONEncoder().encode(requestBodyModel) }
  .responseJSON { … }
  .responseError {
    // handle errors
  }
  .resume()
```

### Affect on SemVer

This change is purely additive and doesn't break any existing APIs.

Note that the existing `setJSON(_ json: Any)` still encodes the body on the main thread, and still silently ignores encoding errors. I considered updating that method to use the new async methods, but I think that would be a breaking change, so I left it as is.

### Test Coverage

All existing tests continue to pass without changes. I added new tests for the new async methods, but I didn't cover them exhaustively.

### CODE REVIEW

**Comment by nonsensery** [comment]
Looks like CI is using Xcode 9.3 / Swift 4.1 (I was using Xcode 10.1 / Swift 4.2). Updated the code to work with those.

**Comment by angelodipaolo** [comment]
We haven't been good about keeping the CI configuration updated. I'll update it to build with Xcode 10.

**Comment by nonsensery** [comment]
Hmm, build failed again on Travis:
```
/Users/travis/build/Electrode-iOS/ELWebService/Source/Core/ServiceTask.swift:41:31: error: use of undeclared type 'AsyncDataProvider'
    private var bodyProvider: AsyncDataProvider?
                              ^~~~~~~~~~~~~~~~~
```
I'm not sure why it can't find that type. It build find locally for me in Xcode 9.3 and 10.1

**Comment by angelodipaolo** [comment]
ahh looks like those files are missing from the static target.

**Pull request merged**
